public class Test_employee
    {
        public void test_employeer()
        {
            employee myEmployee = new employee("Alma", 100.00, 2004, 15, 20.00);
            if(myEmployee.getName()=="Alma")
            {
                System.out.println("correct1");
            }
            else
            {
                System.out.println("Error1");
            }
            if(myEmployee.getSalary()==100)
            {
                System.out.println("correct2");
            }
            else
            {
                System.out.println("Error2");
            }
            if(myEmployee.getYbirth()==2004)
            {
                System.out.println("correct3");
            }
            else
            {
                System.out.println("Error3");
            }
            if(myEmployee.getAge()==15)
            {
                System.out.println("correct4");
            }
            else
            {
                System.out.println("Error4");
            }
            if(myEmployee.getPercentage()==120.00)
            {
                System.out.println("correct5");
            }
            else
            {
                System.out.println("Error5");
            }
            myEmployee.setName("Nico");
            myEmployee.setSalary(200.00);
            myEmployee.setYbirth(2000);
            myEmployee.setAge(19);
            myEmployee.setPercentage(30.00);
                    if(myEmployee.getName()=="Nico")
            {
                System.out.println("correct1");
            }
            else
            {
                System.out.println("Error1");
            }
            if(myEmployee.getSalary()==200)
            {
                System.out.println("correct2");
            }
            else
            {
                System.out.println("Error2");
            }
            if(myEmployee.getYbirth()==2000)
            {
                System.out.println("correct3");
            }
            else
            {
                System.out.println("Error3");
            }
            if(myEmployee.getAge()==19)
            {
                System.out.println("correct4");
            }
            else
            {
                System.out.println("Error4");
            }
            if(myEmployee.getPercentage()==260.00)
            {
                System.out.println("correct5");
            }
            else
            {
                System.out.println("Error5");
            }
    }
    }