public class Test{
    public void test(){
        Bank b = new Bank();
        Account acc1 = new Account(100, 50000, 1000, "Parry Hotter");
        Account acc2 = new Account(101, 80000, 1000, "Germione Hranger");
        Account acc3 = new Account(102, 70000, 1000, "Mraco Dalfoy");
        
        b.addAccount(acc1);
        b.addAccount(acc2);
        if(b.getAccount(0)==acc1){
            System.out.println("c1");
        }
        else{
            System.out.println("e1");
        }
        if(b.getAccount(1)==acc2){
            System.out.println("c2");
        }
        else{
            System.out.println("e2");
        }
        if(b.getAccount(2)==null){
            System.out.println("c3");
        }
        else{
            System.out.println("e3");
        }
        if(b.removeAccount(111)==null){
            System.out.println("c4");
        }
        else{
            System.out.println("e4");
        }
        if(b.removeAccount(101)==acc2){
            System.out.println("c5");
        }
        else{
            System.out.println("e5");
        }
        b.addAccount(acc3);
        if(b.getAccount(0)==acc1){
            System.out.println("c6");
        }
        else{
            System.out.println("e6");
        }
        if(b.getAccount(1)==acc3){
            System.out.println("c7");
        }
        else{
            System.out.println("e7");
        }
        if(b.getAccount(2)==null){
            System.out.println("c8");
        }
        else{
            System.out.println("e8");
        }
        if(b.sumAccount()==120000){
            System.out.println("c9");
        }
        else{
            System.out.println("e9");
        }
        acc1.deposit(3000);
        if(acc1.getBalance()==53000){
            System.out.println("c1");
        }
        else{
            System.out.println("e10");
        }
        acc3.withdraw(3000);
        if(acc3.getBalance()==67000){
            System.out.println("c11");
        }
        else{
            System.out.println("e11");
        }
        if(b.sumAccount()==120000){
            System.out.println("c12");
        }
        else{
            System.out.println("e12");
        }
        if(acc1.withdraw(100000)==54000){
            System.out.println("c13");
        }
        else{
            System.out.println("e13");
        }
        if(b.sumAccount()==120000){
            System.out.println("c14");
        }
        else{
            System.out.println("e14");
        }
        if(acc1.getDatabaseId().equals("PARRY_HOTTER_100")){
            System.out.println("c15");
        }
        else{
            System.out.println("e15");
        }
        if(b.countDbldWith("RA")==1){
            System.out.println("c16");
        }
        else{
            System.out.println("e16");
        }
        b.print();
    }
}